#include "headers.hpp"

Weapon::Weapon(std::string name,
               short rarity,
               short firing_mode,
               short ammo_type,
               sf::Int16 magazine_capacity,
               int reload_time,
               int burst_count,
               int firing_rate,
               int recoil_delay,
               int stand_spread,
               int move_spread,
               int switch_delay,
               int player_damage,
               int unit_range,
               int bullet_speed,
               double bullet_falloff,
               double headshot_multiplier,
               double obstacle_multiplier,
               double passive_slowdown,
               double shooting_slowdown,
               bool potato_swap) : name (name),
                                   rarity (rarity),
                                   firing_mode (firing_mode),
                                   ammo_type (ammo_type),
                                   magazine_capacity (magazine_capacity),
                                   reload_time (reload_time),
                                   burst_count (burst_count),
                                   firing_rate (firing_rate),
                                   recoil_delay (recoil_delay),
                                   stand_spread (stand_spread),
                                   move_spread (move_spread),
                                   switch_delay (switch_delay),
                                   player_damage (player_damage),
                                   unit_range (unit_range),
                                   bullet_speed (bullet_speed),
                                   bullet_falloff (bullet_falloff),
                                   headshot_multiplier (headshot_multiplier),
                                   obstacle_multiplier (obstacle_multiplier),
                                   passive_slowdown (passive_slowdown),
                                   shooting_slowdown (shooting_slowdown),
                                   potato_swap (potato_swap)
{
    //
}
