#include "headers.hpp"

Weapon::Weapon(std::string name,
               Rarity rarity,
               FiringMode firing_mode,
               AmmoType ammo_type,
               sf::Int16 magazine_capacity,
               int burst_count,
               int stand_spread,
               int move_spread,
               int player_damage,
               int unit_range,
               int Projectile_speed,
               double firing_rate,
               double recoil_delay,
               double switch_delay,
               double reload_time,
               double Projectile_falloff,
               double headshot_multiplier,
               double obstacle_multiplier,
               double passive_slowdown,
               double shooting_slowdown,
               bool potato_swap = true,
               bool is_throwable = false,
               const std::function<void(Projectile*)> action = [](Bullet*){}) : name (name),
                                                                                rarity (rarity),
                                                                                firing_mode (firing_mode),
                                                                                ammo_type (ammo_type),
                                                                                magazine_capacity (magazine_capacity),
                                                                                burst_count (burst_count),
                                                                                stand_spread (stand_spread),
                                                                                move_spread (move_spread),
                                                                                player_damage (player_damage),
                                                                                unit_range (unit_range),
                                                                                Projectile_speed (Projectile_speed),
                                                                                firing_rate (firing_rate),
                                                                                recoil_delay (recoil_delay),
                                                                                switch_delay (switch_delay),
                                                                                reload_time (reload_time),
                                                                                Projectile_falloff (Projectile_falloff),
                                                                                headshot_multiplier (headshot_multiplier),
                                                                                obstacle_multiplier (obstacle_multiplier),
                                                                                passive_slowdown (passive_slowdown),
                                                                                shooting_slowdown (shooting_slowdown),
                                                                                potato_swap (potato_swap),
                                                                                is_throwable (is_throwable),
                                                                                action (action)
{
    //
}
