name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false

  build_release:
    name: Build Release
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: linux.AppImage
          - os: windows-latest
            release_suffix: windows.zip
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libsfml-dev
          sed -i 's#usr/lib#usr/lib/x86_64-linux-gnu#g' Makefile
          make appimage release client server package
          mv *.AppImage SurvRoyale-${{ github.ref_name }}-x86_64-linux.AppImage

      - name: Run Windows Build
        if: matrix.os == 'windows-latest'
        run: |
          C:\msys64\usr\bin\wget.exe https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-10.0.0-msvcrt-r1/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64msvcrt-10.0.0-r1.7z
          7z x winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64msvcrt-10.0.0-r1.7z
          call build-windows.bat workflow
          7z a -tzip SurvRoyale-${{ github.ref_name }}-x86_64-windows.zip build
        shell: cmd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: SurvRoyale-${{ github.ref_name }}-x86_64-${{ matrix.release_suffix }}
